global using MediatR;
global using Messaging.Domain.SeedWork;
global using System.Data;
global using Microsoft.EntityFrameworkCore.Design;
global using Messaging.Infrastructure.Extensions;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Storage;
global using Messaging.Domain.AggregatesModel.MessageAggregate;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
